### PR TITLE
Add parameter GlobalKnownHostsFile and UserKnownHostsFile

### PR DESCRIPTION
**Pull request by MemberIT**

### CODE REVIEW

**Comment by tersmitten** [comment]
Nice addition!

Are you in the mood to add this one too? https://github.com/Oefenweb/ansible-ssh-client/issues/4

**Comment by tersmitten** [comment]
And we could make it a `list` instead of a `string`. What do you think?

**Comment by MemberIT** [comment]
> Are you in the mood to add this one too? #4

Yep

> And we could make it a `list` instead of a `string`. What do you think?

This is a good idea.

I will correct PR later.

**Comment by tersmitten** [comment]
Thanks in advance

**Comment by MemberIT** [comment]
@tersmitten Done

**Comment by tersmitten** [comment]
Fixes #4

**Pull request merged**
